# Generated by Django 6.0 on 2025-12-14 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(default='шт', help_text='Единица измерения (шт, кг, г, л и т.д.)', max_length=20, verbose_name='Единица измерения'),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.DecimalField(decimal_places=3, help_text='Вес или количество', max_digits=10, verbose_name='Вес/Количество'),
        ),
    ]
